language: java
sudo: true
jdk:
  - openjdk8

services:
  - mysql

before_install:
  - mysql -e 'USE mysql; SOURCE doc/mybatis-helper-test.sql;'
  - mysql -e "USE mysql;GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '123456' WITH GRANT OPTION;FLUSH PRIVILEGES;"

after_success:
  - bash <(curl -s https://codecov.io/bash)