language: java
sudo: true
jdk:
  - openjdk8
script: "mvn cobertura:cobertura"
services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS demo;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS database1;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS database2;'
  - mysql -e 'USE demo; SOURCE doc/mybatis-helper-test.sql;'
  - mysql -e 'USE database1; SOURCE doc/mybatis-helper-test.sql;'
  - mysql -e 'USE database2; SOURCE doc/mybatis-helper-test.sql;'
  - mysql -e "USE mysql;UPDATE user SET password=PASSWORD('123456') WHERE user='root';FLUSH PRIVILEGES;"
after_success:
  - bash <(curl -s https://codecov.io/bash)