language: java
sudo: true
jdk:
  - openjdk8
env:
  global:
    - CODECOV_TOKEN=17250443-7c26-4881-b499-ba660e61613c
services:
  - mysql

before_install:
  - pip install --user codecov
  - mysql -e 'CREATE DATABASE IF NOT EXISTS demo;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS database1;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS database2;'
  - mysql -e 'USE demo; SOURCE doc/mybatis-helper-test.sql;'
  - mysql -e 'USE database1; SOURCE doc/mybatis-helper-test.sql;'
  - mysql -e 'USE database2; SOURCE doc/mybatis-helper-test.sql;'
  - mysql -e "USE mysql;GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '123456' WITH GRANT OPTION;FLUSH PRIVILEGES;"

after_success:
  - codecov