server.port: 8080

#打印执行sql
logging.level.io.github.happytimor.mybatis.helper.single.database.test.mapper: debug

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

#配置数据源
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/mybatis_helper_demo?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: "root"
    password: "123456"
    driverClassName: "com.mysql.cj.jdbc.Driver"