server.port: 8080

#打印执行sql
logging.level.io.github.happytimor.mybatis.helper.single.database.test.mapper: info

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

#配置数据源
spring:
  datasource:
    url: jdbc:h2:mem:mybatis_helper_demo
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always # 确保每次启动时都初始化
    schema: classpath:mybatis-helper-test.sql # 初始化表结构
  h2:
    console:
      enabled: true # 启用 H2 控制台
      path: /h2-console # 控制台访问路径
#
#    url: "jdbc:mysql://localhost:3306/mybatis_helper_demo?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
#    username: "root"
#    password: "123456"
#    driverClassName: "com.mysql.cj.jdbc.Driver"